In [1]:
import numpy as np

In [11]:
A = np.array([[1, 2, 3], [5, 3, 6], [7, 4, 3]])
B = np.array([1 ,-2 , 9])

In [12]:
A

array([[1, 2, 3],
       [5, 3, 6],
       [7, 4, 3]])

In [13]:
B

array([ 1, -2,  9])

In [15]:
# X = inversa de  A  *  B

inv_A = np.linalg.inv(A)
inv_A

array([[-0.41666667,  0.16666667,  0.08333333],
       [ 0.75      , -0.5       ,  0.25      ],
       [-0.02777778,  0.27777778, -0.19444444]])

In [20]:
# Resolvendo normal 

x = np.dot(inv_A, B)


# resolvendo por solve

matriz_solve = np.linalg.solve(A,B)
matriz_solve

array([ 0.        ,  4.        , -2.33333333])

In [16]:
# provando que é inversa
matriz_I = np.dot(A, inv_A)
matriz_I

array([[ 1.00000000e+00, -1.11022302e-16,  0.00000000e+00],
       [-2.42861287e-16,  1.00000000e+00,  0.00000000e+00],
       [-6.59194921e-17, -1.11022302e-16,  1.00000000e+00]])